/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ThucHanh3;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author ADMIN
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    public Chat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDomain = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHopThoai = new javax.swing.JTextArea();
        txtTinNhan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Domain");

        txtDomain.setText("localhost");

        txtHopThoai.setColumns(20);
        txtHopThoai.setRows(5);
        jScrollPane1.setViewportView(txtHopThoai);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDomain, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtTinNhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTinNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Hàm xử lý sự kiện khi nhấn nút Send (jButton1)
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        byte []sendData;         // Buffer chứa dữ liệu gửi đi (dạng byte)
        DatagramSocket socket = null;  // Socket để gửi (nên khai báo bên ngoài nếu cần dùng lại)
        // String strContent = ""; // Biến này không được dùng để cập nhật JTextArea ở đây

        try {
            // 1. Tạo DatagramSocket (Client không cần bind vào port cố định để gửi)
            socket = new DatagramSocket(); 
            
            // 2. Lấy địa chỉ đích từ ô txtDomain
            String domain = this.txtDomain.getText(); 
            InetAddress ipServer = InetAddress.getByName(domain); // Phân giải địa chỉ
            
            // 3. Lấy cổng đích (hardcode là 1234, phải khớp với port server đang nghe)
            int port = 1234; 
            
            // 4. Lấy nội dung tin nhắn từ ô txtTinNhan
            String stSend = this.txtTinNhan.getText(); 
            
            // 5. Chuyển tin nhắn thành mảng byte
            sendData = stSend.getBytes("UTF-8"); // Nên chỉ định encoding UTF-8
            
            // 6. Tạo DatagramPacket chứa dữ liệu, độ dài, địa chỉ và cổng đích
            DatagramPacket sendPacket = new DatagramPacket(sendData, sendData.length, ipServer, port);
            
            // 7. Gửi gói tin đi
            socket.send(sendPacket); 
            System.out.println("Sent to " + ipServer + ":" + port + " - Data: " + stSend);
            
            // 8. Hiển thị tin nhắn đã gửi lên khu vực chat của chính mình
            // Cần phải lấy nội dung cũ và nối thêm vào
            String currentChat = txtHopThoai.getText();
            txtHopThoai.setText(currentChat + "Gui: " + stSend + "\n");
            
            // 9. Xóa nội dung ô nhập tin nhắn sau khi gửi
            txtTinNhan.setText("");

            // --- LỖI: GỬI LẦN NỮA KHÔNG CẦN THIẾT ---
            // Dòng này gửi lại cùng một tin nhắn một lần nữa. Cần xóa đi.
            // socket.send(sendPacket); 
            // strContent += "\nGui: " + stSend; // Dòng này không cập nhật giao diện

        } catch (Exception e) {
            // Nên hiển thị lỗi cho người dùng biết
            JOptionPane.showMessageDialog(this, "Lỗi khi gửi tin nhắn: " + e.getMessage());
            e.printStackTrace(); // In chi tiết lỗi ra console để debug
        } finally {
             // 10. Đóng socket sau khi gửi xong
            if (socket != null && !socket.isClosed()) {
                socket.close(); 
                System.out.println("Send socket closed.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new Chat().setVisible(true);
            }
        });
    }
    
    public String getContentChat(){
        return this.txtHopThoai.getText();
        
    }
    public void setContentChat(String t){
        this.txtHopThoai.setText(t);
             
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDomain;
    private javax.swing.JTextArea txtHopThoai;
    private javax.swing.JTextField txtTinNhan;
    // End of variables declaration//GEN-END:variables
}
